### ISSUE TITLE
Partial switch to Guzzle

### ISSUE THREAD

**Issue by mattwire** [eileenmcnaughton/nz.co.fuzion.civixero#107]
https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/commit/9a9cbafcfb90dfae184df82eca434e218b1e5848

@eileenmcnaughton this doesn't work. It switched from a GET to a POST and also the call to getGuzzleClient gets redirected via the magic method to __call().

As this is an external library I think the better solution would be to switch to the Xero SDK rather than modify our existing library.

**Comment by eileenmcnaughton** [comment]
@mattwire yeah OK - that existing library kinda 'was' the Xero SDK once
