### ISSUE TITLE
CiviXero Invoice Push Job talks to Xero even when $save === FALSE

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.civixero#11]
I expected that when my implementation of hook_civicrm_accountPushAlterMapped() set the $save parameter to FALSE, that CiviXero would not talk to Xero, as no data was being pushed. But it does.

In CRM_CiviXero_Invoice::push() ...

 - getAccountsInvoice returns FALSE
 - pushToXero() doesn't push anything to Xero, but talks to Xero and returns an array of Invoices in $result['Invoices']['Invoice']
 - this array is JSON-encoded and written into the civicrm_account_invoice table

I expected that when getAccountsInvoice() returns FALSE, pushToXero() would not be called and the accounts_needs_update flag would be set to 0.

I'm happy to contribute a PR for this, but wanted to check first if there was a need for pushToXero() to be called.

**Comment by kenwest** [comment]
BTW, in test that array of Invoices has 54 members, and I think it's more in production.

**Comment by eileenmcnaughton** [comment]
You are making sense - even if we should both be in bed!
