### ISSUE TITLE
Problems arising from update to 2.1.0 from 2.0.2

### ISSUE THREAD

**Issue by Upperholme** [eileenmcnaughton/nz.co.fuzion.civixero#120]
Just updated my installation of this extension to 2.1.0 and came across a couple of issues arising:

1. The menu items for 'Xero Settings' and 'Xero Authorise' appear at the top level of the CiviCRM main menu. I think they were previously in the Administer menu.
2. Also can't see any menu items for the error logs.
3. In my install, the Admin status page - Administer > Administration Console > System Status refused to load. Looking at the apache error log I see:

Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Civi\\Api4\\AccountContact' not found in /home/vcare/sites/default/wp-content/uploads/civicrm/ext/nz.co.fuzion.civixero/Civixero.php:119

Stack trace:\n#0 /home/vcare/sites/default/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(279): civixero_civicrm_check(Array, Array, false)

#1 /home/vcare/sites/default/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php(136): CRM_Utils_Hook->runHooks(Array, 'civicrm_check', 3, Array, Array, false, NULL, NULL, NULL)

#2 /home/vcare/sites/default/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(314): CRM_Utils_Hook_WordPress->invokeViaUF(3, Array, Array, false, NULL, NULL, NULL, 'civicrm_check')

#3 /home/vcare/sites/default/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(251): Civi\\Core\\CiviEventDispatcher::delegateToUF(Object(Civi\\Core\\Event\\GenericHookEvent), 'hook_civicrm_ch...', Object(Civi\\Core\\UnoptimizedEventDispatcher))

#4 /home/v...', referer: https://my.domain/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fa%2F

Disabling the extension enabled the System Status page to load correctly.

NB: This is all using PHP 7.3

**Comment by mattwire** [comment]
@Upperholme This sounds like you need to update accountsync as well

**Comment by Upperholme** [comment]
It's reporting that v1.4 of the account sync extension is installed. I don't see a more recent version being available. Maybe I should install from the master branch, given that v1.4 looks to be pretty old (Sept 2020)?

**Comment by eileenmcnaughton** [comment]
lol magic

**Comment by Upperholme** [comment]
We aim to please ;-)
