### ISSUE TITLE
Bank Transaction logic in CRM_Civixero_Invoice::savePushResponse()

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.civixero#13]
I'm concerned by the Bank Transaction logic in CRM_Civixero_Invoice::savePushResponse().

When the account_invoice is first created, $record['accounts_invoice_id'] will be empty. So after the Push job the account_invoice record is left unchanged, since the 'BankTransactions' element is empty, and 'accounts_needs_update' is still 1. Then when a subsequent Pull is run, the invoice data is set and accounts_needs_update is set to 0.

I think you need to have a savePushReponse function in the CRM_Civixero_BankTransaction class which overrides this function.

Alternately, you might be better testing $result['BankTransactions']['BankTransaction']['BankTransactionID'] rather than $record['accounts_invoice_id'] to see it it is a Bank Transaction.

**Comment by eileenmcnaughton** [comment]
I think I might extract a function out for the 4-5 line block around here

https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/pull/12/files#diff-876ca9833ea4bc480b2f7d004bc15865R414

putting one function on Invoice &overriding it on Bank Transaction.

NB - the PULL hasn't been applicable so far on bank transactions & is entirely untested / unused.

**Comment by kenwest** [comment]
When I first looked at your code I wondered why you weren't pulling BTs, but then I found Xero users could create a bunch of BTs doing a reconciliation then drop them all and start again. Synchronisation nightmare!

**Comment by eileenmcnaughton** [comment]
yes & the request on the BTs has been just to push them - hopefully we can say - if you want a real sync then go the invoice way

**Comment by kenwest** [comment]
May I just clarify something? I see that for Invoices the accounts_invoice_id value is left NULL by the Push and then set by a subsequent Pull. What is the reason for not setting it during the Push?

**Comment by eileenmcnaughton** [comment]
that's the invoice id returned from Xero - probably no good reason if Xero returns it on the push

**Comment by kenwest** [comment]
Just a thought re "hopefully we can say". A possibility with the BT Pull (if you were forced to implement it) would be to add an "end_date" parameter to the job. Thus setting the parameters to something like ...

    start_date=-2 days
    end_date=yesterday

... would wait 24 hours before pulling BTs, giving them time to settle down.

**Comment by eileenmcnaughton** [comment]
I think this was resolved....
