### ISSUE TITLE
Not pushing DELETED invoices to Xero

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.civixero#14]
When I delete an Invoice in Xero ...

1. The Invoice is pulled to CiviCRM
2. The update contribution status job updates the Contribution
3. The Contribution is pushed to Xero, which rejects the push

... and the civicrm_accounts_invoice row contains ...

    accounts_status_id = 3
    error_data = ["Invoice not of valid status for modification"]

My initial thought was to use the accountPushAlterMapped() hook to prevent the Push, but then I thought a better solution might be to modify getContributionsRequiringPushUpdate() to not return AccountInvoices where accounts_status_id = 3

Thoughts?

**Comment by eileenmcnaughton** [comment]
I guess they should Push if there is an EXISTING invoice (update to cancelled) but  not create a new one?

**Comment by kenwest** [comment]
The function _accountsync_create_account_invoice() is called when a contribution is created or edited, and this doesn't set 'accounts_status_id'. As far as I can see 'accounts_status_id' is only set by the Pull job or by recording the response after a Push. So 'accounts_status_id == 3' can only be true if the Invoice has been DELETED or VOIDED in Xero.

**Comment by eileenmcnaughton** [comment]
OK sure - because that is the Xero status isn't it! OK - makes sense.

Does this work?

    $criteria = array(
      'accounts_needs_update' => 1,
      'plugin' => 'xero',
      'connector_id' => $params['connector_id'],
      'accounts_status_id' => array('NOT IN', 3),
      'options' => array(
        'sort' => 'error_data',
        'limit' => $limit,
      ),
    );

**Comment by kenwest** [comment]
I'll give that a go

**Comment by kenwest** [comment]
Eileen,

I get the following error ...

    Jun 08 21:05:23  [info] $backTrace = #0 sites/all/modules/civicrm/CRM/Core/Error.php(894): CRM_Core_Error::backtrace("backTrace", TRUE)
    #1 [internal function](): CRM_Core_Error::exceptionHandler(Object(DB_Error))
    #2 sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error))
    #3 sites/all/modules/civicrm/packages/DB.php(976): PEAR_Error->PEAR_Error("DB Error: syntax error", -2, 16, (Array:2), "SELECT * \n FROM civicrm_account_invoice \n \n WHERE ( accounts_status_id 0 )...")
    #4 sites/all/modules/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-2, 16, (Array:2), "SELECT * \n FROM civicrm_account_invoice \n \n WHERE ( accounts_status_id 0 )...")
    #5 sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -2, NULL, NULL, "SELECT * \n FROM civicrm_account_invoice \n \n WHERE ( accounts_status_id 0 )...", "DB_Error", TRUE)
    #6 sites/all/modules/civicrm/packages/DB/mysql.php(899): DB_common->raiseError(-2, NULL, NULL, NULL, "1064 ** You have an error in your SQL syntax; check the manual that correspon...")
    #7 sites/all/modules/civicrm/packages/DB/mysql.php(328): DB_mysql->mysqlRaiseError()
    #8 sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("SELECT * \n FROM civicrm_account_invoice \n \n WHERE ( accounts_status_id 0 )...")
    #9 sites/all/modules/civicrm/packages/DB/DataObject.php(2442): DB_common->query("SELECT * \n FROM civicrm_account_invoice \n \n WHERE ( accounts_status_id 0 )...")
    #10 sites/all/modules/civicrm/packages/DB/DataObject.php(441): DB_DataObject->_query("SELECT * \n FROM civicrm_account_invoice \n \n WHERE ( accounts_status_id 0 )...")
    #11 sites/all/modules/civicrm/api/v3/utils.php(931): DB_DataObject->find()
    #12 sites/all/modules/civicrm/api/v3/utils.php(1253): _civicrm_api3_dao_to_array(Object(CRM_Accountsync_BAO_AccountInvoice), (Array:6), FALSE, "")
    #13 sites/default/files/civicrm/extensions/nz.co.fuzion.accountsync/api/v3/AccountInvoice.php(54): _civicrm_api3_basic_get("CRM_Accountsync_BAO_AccountInvoice", (Array:6))
    #14 sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_account_invoice_get((Array:6))
    #15 sites/all/modules/civicrm/Civi/API/Kernel.php(96): Civi\API\Provider\MagicFunctionProvider->invoke((Array:9))
    #16 sites/all/modules/civicrm/api/api.php(23): Civi\API\Kernel->run("account_invoice", "get", (Array:6), NULL)
    #17 sites/all/modules/civicrm/api/api.php(43): civicrm_api("account_invoice", "get", (Array:6))
    #18 sites/default/files/civicrm/extensions/nz.co.fuzion.civixero/CRM/Civixero/Invoice.php(342): civicrm_api3("account_invoice", "get", (Array:5))
    #19 sites/default/files/civicrm/extensions/nz.co.fuzion.civixero/CRM/Civixero/Invoice.php(131): CRM_Civixero_Invoice->getContributionsRequiringPushUpdate((Array:3), 25)
    #20 sites/default/files/civicrm/extensions/nz.co.fuzion.civixero/api/v3/Civixero/Invoicepush.php(41): CRM_Civixero_Invoice->push((Array:3), 25)
    #21 sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_civixero_invoicepush((Array:3))
    #22 sites/all/modules/civicrm/Civi/API/Kernel.php(96): Civi\API\Provider\MagicFunctionProvider->invoke((Array:9))
    #23 sites/all/modules/civicrm/api/api.php(23): Civi\API\Kernel->run("Civixero", "invoicepush", (Array:2), NULL)
    #24 sites/all/modules/civicrm/CRM/Core/JobManager.php(131): civicrm_api("Civixero", "invoicepush", (Array:2))
    #25 sites/all/modules/civicrm/CRM/Core/JobManager.php(110): CRM_Core_JobManager->executeJob(Object(CRM_Core_ScheduledJob))
    #26 sites/all/modules/civicrm/CRM/Admin/Page/Job.php(155): CRM_Core_JobManager->executeJobById("26")
    #27 sites/all/modules/civicrm/CRM/Core/Page/Basic.php(178): CRM_Admin_Page_Job->browse(NULL, NULL)
    #28 sites/all/modules/civicrm/CRM/Admin/Page/Job.php(140): CRM_Core_Page_Basic->run()
    #29 sites/all/modules/civicrm/CRM/Core/Invoke.php(312): CRM_Admin_Page_Job->run((Array:3), NULL)
    #30 sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:13))
    #31 sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
    #32 sites/all/modules/civicrm/drupal/civicrm.module(489): CRM_Core_Invoke::invoke((Array:3))
    #33 [internal function](): civicrm_invoke("admin", "job")
    #34 includes/menu.inc(519): call_user_func_array("civicrm_invoke", (Array:2))
    #35 index.php(21): menu_execute_active_handler()
    #36 {main}

I've tried the following options ...

    'accounts_status_id' => array('NOT IN', 3),
    'accounts_status_id' => array('NOT IN', array(3)),
    'accounts_status_id' => array('NOT IN', array('3')),
    'accounts_status_id' => array('NOT IN', array('0' => 3),
    'accounts_status_id' => array('NOT IN', array('0' => '3'),

but each time the SQL includes "WHERE ( accounts_status_id 0 )" so it seems the "NOT IN" is being ignored.

**Comment by kenwest** [comment]
Eileen,

I've thought of an alternate approach, that has the advantage of processing the accounts_invoice and setting the 'accounts_needs_update' flag back to '0'. See PR #15

**Comment by kenwest** [comment]
Closing this as you've merged #15
