### ISSUE TITLE
Getting error: API (Connector, get) does not exist

### ISSUE THREAD

**Issue by yosefromano** [eileenmcnaughton/nz.co.fuzion.civixero#22]
I completed all the installation steps. I'm using Drupal 7.50 and CiviCRM 4.6.19
I am getting this error any time I try to open a contact profile or add an activity to a contact. 
![screen shot 2016-08-07 at 9 08 17 pm](https://cloud.githubusercontent.com/assets/10218159/17469136/53823324-5ce3-11e6-83df-8f5c9be1d5d8.png)

**Comment by eileenmcnaughton** [comment]
Yeah - that's a recent regression - I hit it too. A few patches ago it was fine

**Comment by eileenmcnaughton** [comment]
I pushed up a fix that I think will sort this out
