### ISSUE TITLE
OAuth declarations

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.civixero#3]
Eileen,

My site uses the Drupal OAuth module, so I get "cannot redeclare class" errors in packages/Xero/Xero.php.

To work around that, I'm wrapping the OAuth class declarations in

    if (!class_exists('OAuthException')) {
      ...
    }

Would you like me to create a PR for that?

**Comment by eileenmcnaughton** [comment]
Sure. I'm sure there is a better way of including this class / library now - but happy to include this fix
