### ISSUE TITLE
Setting to push line item including tax amount?

### ISSUE THREAD

**Issue by jitendrapurohit** [eileenmcnaughton/nz.co.fuzion.civixero#32]
Issue - Contribution with taxes are pushed without including tax_amount.

[mapToAccounts()](https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/blob/master/CRM/Civixero/Invoice.php#L178-L196) makes sure the line items are sent inclusive or exclusive of line items.

It seems we don't actually add `tax_amount` to the total amount that is sent to xero. Instead, we set `LineAmountTypes` based on if a contribution contains the `tax_amount`.

Approach to fix -

- If `$line_amount_types` is set to `inclusive` - directly add tax_amount if contribution has it **OR**
- Add an extra setting to include tax amount while pushing to xero and calculate total amount based on its value whether it is enabled or disabled.

@eileenmcnaughton thoughts? I'm more inclined to go with point 2 unless I'm missing something here?

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit can you talk through the use case a bit more here?

In general the concept was about allowing Xero to calculate the tax based on having it configured in Xero - but that was on a simple config

**Comment by jitendrapurohit** [comment]
@eileenmcnaughton yfnz seems to be seeing a case where contribution with tax amount are not being sent with correct `total_amount` to xero. 

For eg: a contribution with `$70`(including tax) are pushed to xero as `$60.87`. 

I think this is because we don't add `tax_amount` to the total lineitem that is calculated from [`mapAccounts()`](https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/blob/master/CRM/Civixero/Invoice.php#L192) function.

See more at https://redmine.fuzion.co.nz/issues/12923#note-44

**Comment by jitendrapurohit** [comment]
>In general the concept was about allowing Xero to calculate the tax based on having it configured in Xero - but that was on a simple config

okay, lemme check for a while on this with pete.

**Comment by eileenmcnaughton** [comment]
The gst amount is configured on per account code basis within Xero
