### ISSUE TITLE
Xero API deprecating TLS 1.0 on 30 June 2018

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.civixero#36]
Xero have just [announced this](https://developer.xero.com/tls1-deprecation).

It seems that using openssl 1.01 or greater will be adequate (the client and server will negotiate TLS 1.1 or 1.2) but just wanted to flag this in case more was needed to make this work.

Cheers!

**Comment by eileenmcnaughton** [comment]
thanks @kenwest I saw that email but had not analysed the impact

**Comment by kenwest** [comment]
@eileenmcnaughton I wrote some code to test what happens when the curl request made in /packages/Xero/Xero.php is sent to the [How's my SSL?](https://www.howsmyssl.com/) site. My production server supports TLS 1.2 and when I run the code it tells me that TLS 1.2 is being used.

**That suggests that provided TLS 1.2 is supported by the CiviCRM host, the current code will continue to work as expected when Xero depreciate TLS 1.0**.

Here's the code ...

    <?php
    //  The following code is copied from /packages/Xero/Xero.php starting at line 154
    //  I commented out the lines which required some application logic but didn't seem
    //  to affect the TLS protocol negotiations. I changed the destination URL to a site
    //  that returns the TLS status.
    
    $ch = curl_init();
    //  if ( $acceptHeader=='pdf' ) {
    //    curl_setopt($ch,CURLOPT_HTTPHEADER,
    //      array (
    //        "Accept: application/".$acceptHeader
    //      )
    //    );
    //  }
    curl_setopt($ch,CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_URL, 'https://www.howsmyssl.com/a/check');
    //  if ( isset($modified_after) && $modified_after != false) {
    //    curl_setopt($ch, CURLOPT_HTTPHEADER, array("If-Modified-Since: $modified_after"));
    //  }
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    $temp_xero_response = curl_exec($ch);
    curl_close($ch);
    
    //  Decode and print the TLS version
    
    $tlsVer = json_decode($temp_xero_response, true);
    echo "Your TSL version is: " . ( $tlsVer['tls_version'] ? $tlsVer['tls_version'] : 'no TLS support' ) . "\n";

**Comment by eileenmcnaughton** [comment]
thank you!

**Comment by kenwest** [comment]
No worries. I'm not sure my test closes off the issue, but it might give people a prompt to upgrade their server.

**Comment by eileenmcnaughton** [comment]
@agileware ping on this

@kenwest I'm pretty sure other things like eWay have been enforcing tls for a while so most servers are probably on TLS - I know Fuzion didn't have to take any server action when eWay? enforced TLS 2 so it's pretty standard

**Comment by eileenmcnaughton** [comment]
We merged a warning on this - I don't think we can do much more
