### ISSUE TITLE
Supported versions of CiviCrm....

### ISSUE THREAD

**Issue by natiki** [eileenmcnaughton/nz.co.fuzion.civixero#38]
Hi @eileenmcnaughton,

Came across your extension and have a few questions.

1) I am looking at integrating this into an existing CiviCRM install. The install is running 4.5.5 but https://civicrm.org/extensions/civixero says the extension only supports 4.2 & 4.4 and is currently in BETA. I am assuming the link on civicrm.org is pretty old and that 4.5.5 is supported?

2) Can you confirm that the TLS 1.2 issue https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/issues/36 has been tested and works  as outbound we are only TLS 1.2?

3) The link you provide http://developer.xero.com/documentation/getting-started/private-applications/ to setup the application returns a 404. As the client already has an SSL certificate can they just use that or do they need a separate one to interact with Xero?

**Comment by eileenmcnaughton** [comment]
Hmm I guess that supports hasn't been updated for a while - really we only support 4.7 & will support 5.0 when that drops (it's an administrative renaming not a major bump). It may work on older versions but I have not touched anything before 4.7 in a few years.

My understanding with TLS is that it's opaque to the extension - it uses what your server has installed & we went through similar things with payment processors. 

Perhaps this is the new link https://developer.xero.com/documentation/auth-and-limits/private-applications

**Comment by natiki** [comment]
Any thoughts on how smooth an upgrade from 4.5.x to 4.7.x is likely to go? :-/

**Comment by eileenmcnaughton** [comment]
If there isn't a lot of custom stuff and you are on a supported php version it is likely to be fine - although I would be very careful about backups & being able to back out, e.g if you hit a data error while upgrading.

Also - use git locally before you start as part of your backup plan

**Comment by natiki** [comment]
Thanks for that.
