### ISSUE TITLE
Invoice Push fails with non-ASCII characters

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.civixero#39]
Hi,

If the Invoice's Reference or a Line Item's Description contains a non-ASCII character, the push will fail with no warning (at the CiviCRM end).

For my purposes I am happy to strip out the occasional accented vowel or right single quote, so I've used filter_var(..., FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW | FILTER_FLAG_STRIP_HIGH) in hook_civicrm_accountPushAlterMapped().

I'm happy to contribute toward a patch that filters text sent to Xero but my approach probably won't work in the wider world.

**Comment by eileenmcnaughton** [comment]
@agileware @jitendrapurohit any thoughts on this - it seems like those filters would make sense & probably would 'do no harm'

**Comment by mattwire** [comment]
@eileenmcnaughton This does not seem to be an issue with version 2.0 and can be closed
