### ISSUE TITLE
Unable to make permanent changes to CiviXero job parameters

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.civixero#43]
Every time I enable or disable a CiviCRM extension, the contents of CRM/Civixero/Job/job.mgd.php are used to regenerate the CiviXero jobs.

So if I have changed the job parameters these changes get lost.

**Comment by eileenmcnaughton** [comment]
Ah - I think there is something that can go in the definition like 'update' => 'never' that can be added to the definition in the mgd file

**Comment by eileenmcnaughton** [comment]
OK - just added a fix for this
