### ISSUE TITLE
Invoice push: Expected one OptionValue but found 0

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.civixero#45]
@eileenmcnaughton it's been a while since I've had the pleasure of raising an issue here!

I'm having an issue whereby I'm getting failures in the Invoice Push Job. The log contains lines like ...
```
[0] => Failed to store 999 ( ) with error Expected one OptionValue but found 0Invoice Push failed
```

Here's the breakdown of how to produce and what's going on ...

- Create a contribution with a NULL payment_instrument_id
  - eg, a Pending contribution has no payment instrument
  - eg, a recurring PayPal Standard contribution has no payment instrument for seond and subsequent contributions (probably a bug)
- Invoke the Push job
- The job invokes CRM_Accountsync_BAO_AccountInvoice::getDerived()
- This baulks at line 101 because 'payment_instrument_id' is unset (despite the best efforts of lines 96-99)
- The exception that's raised gets caught and the job goes on to the next contribution

I think the fix required is to change CRM_Accountsync_BAO_AccountInvoice::getDerived() to move the code on line 101 inside the try/catch block that starts on line 102. The impact of this will be ...

- if the contribution's 'payment_instrument_id' is unset, the job will continue with 2 elements of the contribution unset
  - ['payment_instrument_financial_account_id']
    - this element is not referred to elsewhere
  - ['payment_instrument_accounting_code']
    - this element is only referenced in CRM_Civixero_BankTransaction::mapToAccounts() which I believe is a completely different job.
- this should have no detrimental effects because these elements appear to be unused

I'll try this change and submit a PR if it goes well.

Cheers!

**Comment by kenwest** [comment]
Oh, yes. That PR would be issued against the AccountSync repository. I'll make it refer to this issue to keep things aligned.

**Comment by eileenmcnaughton** [comment]
I think this got resolved
