### ISSUE TITLE
State of play of this extension

### ISSUE THREAD

**Issue by Upperholme** [eileenmcnaughton/nz.co.fuzion.civixero#48]
Hi. I'm working with a client that is looking for tighter integration and streamlining between their existing Civi implementation and their accounting. They're not tied to any particular accounting system as yet. So my question is: is Civixero suitably robust and useable to be a viable option for them, and if so, what level of work might we expect in terms of getting it set up. Will we need to contract with you for assistance/support or will it just work?
Thanks.

**Comment by eileenmcnaughton** [comment]
So in terms of set up - the key things are

1) the initial sync - this won't be an issue if you are starting fresh
2) setting up xero keys - there are instructions in the docs here & I think it's not too hard if you work through it
3) setting up the accounting codes in civi to match the accounting codes in Xero - ie. if the account code in Xero is 800 then the financial account needs to have the same code.

Note that we record sales-tax free amounts in Civi & let Xero handle sales tax in NZ / AU - if your sales tax needs differ it could get more complicated.

Xero allows you to set up a free trial for 30 days & you can start paying if you want to keep the data after that. I'd suggest you give it a go & try it out & see what you think.

Happy to help you here or on chat but if you want something more serious ping Pete for an arrangement

**Comment by Upperholme** [comment]
Really helpful. Thanks you so much. We're currently scoping out options, and if we go further down this road I'll be back.

**Comment by eileenmcnaughton** [comment]
Note that I just released the work Veda did on Oauth 2 support
