### ISSUE TITLE
Connector_Id argument needed in REST call

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.civixero#5]
Eileen, to use the "Queue sync to Xero" link on the Contact Summary page, I need to add an argument to set the connector_id. See https://github.com/kenwest/nz.co.fuzion.civixero/compare/master...kenwest:connector-0

It's a hack, which is why I haven't raised a PR, and I guess you will want to consider which piece of logic sets the connector_id.

**Comment by eileenmcnaughton** [comment]
yes good point - I think the fix to the connector_id fix will make that irrelevant for single connector sites & I might disable the link for multiple connector sites in the short-term

**Comment by kenwest** [comment]
Your push for issue #6 solves this issue
