### ISSUE TITLE
CiviXero with civi 5.xx

### ISSUE THREAD

**Issue by yosefromano** [eileenmcnaughton/nz.co.fuzion.civixero#53]
THe page below says that the extension is only compatible with civi 4.2 and 4.4
https://civicrm.org/extensions/civixero

**Comment by eileenmcnaughton** [comment]
OK I see - I've added a second release - so it shows 5.14 now. I have been using this all along with pretty much every point version so it should work with any 5.x version but I used the current release in the release notes.

Note it isn't approved for automatic install - that dates back to when Civi wouldn't install dependencies but perhaps we should fix that - @agileware-fj what do you think?

**Comment by eileenmcnaughton** [comment]
(it is a little complicated to get started on - since you need to think about an initial sync etc)

**Comment by agileware-fj** [comment]
@eileenmcnaughton I wasn't even aware dependencies installation worked now?  We kinda stopped using the auto install feature some time back...
Although as far as CiviXero is concerned I think before thinking about click to install, the generation and installation of certificates needs to be made easier for the layperson.

**Comment by eileenmcnaughton** [comment]
Yeah - the only way we can do that is becoming an official extension I think - but that might be more a SAAS thing

**Comment by eileenmcnaughton** [comment]
I just tagged release 2.0 against Civi 5.24
