### ISSUE TITLE
Limited to 25 line items

### ISSUE THREAD

**Issue by benasp123** [eileenmcnaughton/nz.co.fuzion.civixero#55]
Hi. Xero is only importing 25 line items, the contribution has 48 line items. There are no obvious errors in Civi or Xero. Using Drupal 7, Webform & Civi. All on the latest version. I've tried multiple times and the same issue persists. Thanks for any help.

**Comment by eileenmcnaughton** [comment]
argh - that sounds like the api default limit - see if this helps https://github.com/eileenmcnaughton/nz.co.fuzion.accountsync/pull/41 (in the related accountsync extension)

**Comment by benasp123** [comment]
Yep, that fixed the issue. Thanks! Might be out of scope for this post... but is there away of forcing Civi to resync the contribution that stopped at row 25 with Xero?

**Comment by eileenmcnaughton** [comment]
Try altering the is_update_needed (or similar) column in civicrm_account_invoice table

**Comment by benasp123** [comment]
That doesn't work. I've tried deleting the original invoice in Xero, but clicking on the link in the Contribution Summary in Civi brings up the deleted Xero record with the status of "deleted". I'm not not sure how to fully delete this record in Xero. Could this be the issue?

**Comment by eileenmcnaughton** [comment]
Ah no - it would have updated it if left in draft state but it's kinda stuck now it's deleted - generally you need to have a new contribution id once you've deleted the xero one as the id is unique

**Comment by benasp123** [comment]
I did try changing the is_update_needed value before deleting the record from Xero. It didn't work, so naturally I made it worse by deleting it from Xero. Not the end of the world. Thanks for your help.
