### ISSUE TITLE
Class 'OAuthSignatureMethod_RSA_SHA1' not found on local install

### ISSUE THREAD

**Issue by adamt-devapp** [eileenmcnaughton/nz.co.fuzion.civixero#56]
Hi,

We are having an issue where we get a fatal error, class not found, when trying to execute a contact push job on a local install.

When running on a live debug site however, the error is not not present.

Any ideas as to why this might be happening?
Are we possibly missing a required PHP library on the local install?

The local setup is running Civi v5.13.5 and PHP 7.2.2 (MAMP)

Here's a screenshot of the error.
![civixero-class-missing](https://user-images.githubusercontent.com/54293902/63306140-8d67a980-c328-11e9-992c-104844630117.png)

Any ideas as to why this might be happening would be greatly appreciated.

Regards,
Adam

**Comment by eileenmcnaughton** [comment]
Is the file present in the file location  above? It's included in  this extension - https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/tree/master/packages/Xero but could be skipped by a .gitignore somewhere?

**Comment by Adam-T-DevApp** [comment]
Yes, the Xero.php file is present.

Copying the extension folder to a live debug site and running doesn't produce the same error which was why I was thinking it may possibly be a PHP library issue on the local version.

**Comment by eileenmcnaughton** [comment]
Hmm - that class is in the same file - so no idea why  it doesn't load but I suspect some difference in the php version/extensions/config

**Comment by adamt-devapp** [comment]
Ok, thanks.
Will have to dig a little further.
Was hoping to get lucky and it's something that may have come up before.

Thanks for getting back to me on this.

**Comment by eileenmcnaughton** [comment]
I think this can be closed. Note the latest release supports Oath2 & is different again
