### ISSUE TITLE
API (Xerosync, trackingcategorypull) does not exist (join the API team and implement it!)

### ISSUE THREAD

**Issue by jrobens** [eileenmcnaughton/nz.co.fuzion.civixero#58]
I can see this api, but my version civicrm doesn't find it. 

Error message is

    API (Xerosync, trackingcategorypull) does not exist (join the API team and implement it!)

**Comment by eileenmcnaughton** [comment]
Looks like  it is 

civixero_trackingcategorypull

so 

Civixero is   the api entity

**Comment by jrobens** [comment]
I can put in a patch setting this line #346 Invoice.php

    $trackingOptions = civicrm_api3('civixero', 'trackingcategorypull', array());

I'll see what I can do to test it. I ended up setting the data structure to [Tracking][TrackingCategory] with Tracking array nesting the TrackingCategory item as per 

https://developer.xero.com/documentation/api/invoices

       <Tracking>
          <TrackingCategory>
            <TrackingCategoryID>e2f2f732-e92a-4f3a9c4d-ee4da0182a13</TrackingCategoryID>
            <Name>Activity/Workstream</Name>

This matters because the validation that was my first catch up doesn't get called.
