### ISSUE TITLE
Job arguments

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.civixero#6]
**CiviXero Invoice Push Job**

This job needs the connector_id argument supplied. Eg, ...

    plugin=xero
    connector_id=0

**CiviXero Pull Jobs**

Scheduled Jobs expects a newline between arguments. So ...

    plugin=xero, start_date=yesterday

... will be read so the plugin parameter has the value "xero, start_date"

**Comment by eileenmcnaughton** [comment]
Can you check whether api default I just pushed resolves this?

**Comment by kenwest** [comment]
Eileen, your push solves the Invoice Push Job issue.
