### ISSUE TITLE
Xero extension breaks merging contacts 

### ISSUE THREAD

**Issue by benasp123** [eileenmcnaughton/nz.co.fuzion.civixero#61]
It looks like this extentsion stops contacts being merged together.

I am trying to merge 2 contacts (individuals). I search for the contact, select both contacts and select merge. Go through the options. A message saying: Contacts Merged, Name has been updated. Contact ID 1951 has been deleted.

The contacts are not merged and no contacts are deleted.

The log file in ConfigAndLog has this message:

[error] $Fatal Error Details = Array ( [callback] => Array ( [0] => CRM_Core_Error [1] => exceptionHandler )

[code] => -5
[message] => DB Error: already exists
[mode] => 16
[debug_info] => UPDATE  civicrm_account_contact  SET contact_id = 1951 , accounts_contact_id = '2bd64d12-13b0-4188-a708-430aa0bb8f5b' , accounts_display_name = 'Neil T - 1501' , last_sync_date = 20191018151509 , accounts_modified_date = 20191018000000 , accounts_data = 'Array' , accounts_needs_update = 0 , connector_id = 0 , plugin = 'xero' , do_not_sync = 0   WHERE (  civicrm_account_contact.id = 2598 )   [nativecode=1062 ** Duplicate entry '1951-0-xero' for key 'contact_id_plugin']
[type] => DB_Error
[user_info] => UPDATE  civicrm_account_contact  SET contact_id = 1951 , accounts_contact_id = '2bd64d12-13b0-4188-a708-430aa0bb8f5b' , accounts_display_name = 'Neil T - 1501' , last_sync_date = 20191018151509 , accounts_modified_date = 20191018000000 , accounts_data = 'Array' , accounts_needs_update = 0 , connector_id = 0 , plugin = 'xero' , do_not_sync = 0   WHERE (  civicrm_account_contact.id = 2598 )   [nativecode=1062 ** Duplicate entry '1951-0-xero' for key 'contact_id_plugin']
[to_string] => [db_error: message="DB Error: already exists" code=-5 mode=callback callback=CRM_Core_Error::exceptionHandler prefix="" info="UPDATE  civicrm_account_contact  SET contact_id = 1951 , accounts_contact_id = '2bd64d12-13b0-4188-a708-430aa0bb8f5b' , accounts_display_name = 'Neil T - 1501' , last_sync_date = 20191018151509 , accounts_modified_date = 20191018000000 , accounts_data = 'Array' , accounts_needs_update = 0 , connector_id = 0 , plugin = 'xero' , do_not_sync = 0   WHERE (  civicrm_account_contact.id = 2598 )   [nativecode=1062 ** Duplicate entry '1951-0-xero' for key 'contact_id_plugin']"]
)

Using latest version of Drupal (7.67) + Civi (5.18.3) + civixero (1.2)

**Comment by jusfreeman** [comment]
@eileenmcnaughton we think this is actually an AccountSync bug and we're tracking it also. Can you move this bug report to AccountSync project? Cheers!

**Comment by eileenmcnaughton** [comment]
@jusfreeman only by closing it here & you open one on account sync

**Comment by jusfreeman** [comment]
Gotcha.

**Comment by benasp123** [comment]
I will close this report. I have opened a new one here: https://github.com/eileenmcnaughton/nz.co.fuzion.accountsync/issues/45
