### ISSUE TITLE
Compatibility with CiviCRM 4.5, 4.6

### ISSUE THREAD

**Issue by Upperholme** [eileenmcnaughton/nz.co.fuzion.civixero#7]
Hi, and thanks for this extension. I'm just starting with it for a client who is also about to start using Xero, so a fair bit of learning all round I guess. First question before I start - is this extension compatible with version 4.5.x and/or 4.6.x of CiviCRM? 

And if not, do you have plans to make it compatible? We are currently working with CiviCRM 4.5.x, but as I understand it 4.6 is going to be the new LTS so it would make sense to aim for that assuming all our required extensions can support 4.6

**Comment by eileenmcnaughton** [comment]
Yes, it works on 4.6 - however, I did a piece of work last month on it to create the possibility of more than one connector per site (depending on the contact_id of the account_code of the line item they get directed to one or the other & that is still a little in progress. Ken has hit a couple of bugs (against 4.6) & raised issues & some PRs so you might want to just check out the issue queue - I know at least one needs to be resolved - although it's relatively minor - ensuring the connector_id defaults to 0.

**Comment by kenwest** [comment]
CiviXero is working nicely on 4.6, and all the issues I've had I've referred to this repo.
