### ISSUE TITLE
Oauth rate limit exceeded?

### ISSUE THREAD

**Issue by Upperholme** [eileenmcnaughton/nz.co.fuzion.civixero#78]
For some reason one of sites has stopped syncing properly. I've made no changes.

The Civi log now reports this line twice every 5 minutes:

`[info] Oath rate exceeded: <br/>`

I'm assuming this is a typo in the code, and it should be reporting "Oauth rate exceeded". However, the docs at https://developer.xero.com/documentation/oauth2/limits suggest that we are a very long way from reaching the limits.

Also, every thirty minutes I'm seeing:

`[info] $CiviXeroDebug = Storing renewed token.`

Any pointers most welcome.

**Comment by Upperholme** [comment]
And I have a growing number of invoice errors listed at /civicrm/xero/errorlog?for=invoice

All of these report the same error date:

`A validation exception occurred

An existing contact could not be found using the specified contact details. The contact name field is required to create a new contact.`

**Comment by Upperholme** [comment]
Further information that might help to explain what's happening: at /civicrm/a/#/accounts/contact/sync I'm seeing a number of unmatched contacts. Specifically it reads "Resolving 10 out of 38 of unmatched contacts in your accounting system." It's not clear from this page what these unmatched contacts, how they came about, or how to resolve them (assuming they need to be resolved).

**Comment by eileenmcnaughton** [comment]
It rates limits on the ip address - and if one or more sites has syncs that keep failing it throttles the server. Cleaning out entries that aren't syncing (setting is_needs_update to 0) helps. There is also aa technical fix we could do (bundling more calls into less requests) but it's never hit the top of the priority list

**Comment by Upperholme** [comment]
Apologies - you're going to have to help me on this. Where/how can I set is_needs_update to 0 ?

**Comment by eileenmcnaughton** [comment]
Do you have mysql access? I think @jitendrapurohit maybe did a UI interface if not

**Comment by Upperholme** [comment]
Yes, I have mysql access.

**Comment by Upperholme** [comment]
Looking at the database tables I see 2: civicrm_account_contact and civicrm_account_invoice. Both tables include a column called accounts_needs_update which has the comment "include in next push to accounts", which sounds useful in this context. Should I be identifying the contacts and invoices that are not syncing and setting accounts_needs_update for these rows to be 0 ?

**Comment by eileenmcnaughton** [comment]
yep!

**Comment by Upperholme** [comment]
Hmm. So I edited all of the entries in both tables where accounts_needs_update = 1 to change the value to 0.
Then I added a couple of new invoices in Civi and waited to see if they got pushed up to Xero.
Result: failure. exactly the same error message as before:
`A validation exception occurred An existing contact could not be found using the specified contact details. The contact name field is required to create a new contact.`

Looking again at the database tables, most (all?) of the rows where I had set accounts_needs_update to 0 are now set to 1 again, so I need  some help with this, as I'm joust going round in circles, and not understanding what is actually happening here.

Looking at the first example of a row in the database table where the accounts_needs_update has been re-set to 1, I can see that it pertains to an invoice where, in Xero it has been Deleted, and in Civi it has been set to Cancelled. So I can't see why either Civi or Xero would want to indicate that data pertaining to this invoice should be synced. I tried deleting the contribution record in Civi but it won't let me do that.

I don't understand why I have bunch of contribution records that apparently refuse to get out of the way. I'm almost certain this is because our people are doing something (either in Civi or in Xero) that the sync can't cope with, but I don't know what it is.

**Comment by Upperholme** [comment]
Bump. Could really use some assistance here to help me understand why my sync has stopped working, so that I can fix it and get it up and running again.

**Comment by eileenmcnaughton** [comment]
@Upperholme so first thing - you don't share the server with any other sites do you (it's throttled by IP)

The accounts_needs_update flag is updated to 1 whenever a contribution is edited - did you edit them?

I assume you are using latest everything?

**Comment by Upperholme** [comment]
Thanks. There is one other site using the same IP address which also has a Civixero sync in place. No errors reported there. And what I'm seeing now, having done nothing for several days, is that I'm seeing no errors reported at /civicrm/xero/errorlog or civicrm/xero/errorlog?for=invoice and the scheduled job logs look clear of errors also.

Looking at my database I see 42 records in civicrm_account_contact where accounts_needs_update = 1. civicrm_account_invoice has no records where accounts_needs_update = 1. 

Contact records do get edited/updated over time in CiviCRM, and I'm aware that the book-keeper is quite frequently editing contact records in Xero (often when the contact first gets pushed to Xero they'll tweak it to suit their requirements). I'm not sure if this is an issue?

As I'm seeing no current errors I'm going to try to push a new invoice and contact into Xero and we'll see what happens.

**Comment by Upperholme** [comment]
That didn't work. I created two transactions (memberships), and on the next sync both failed.I think this is because of all the rows in civicrm_account_contact where accounts_needs_update = 1. 
If I change all of those rows to accounts_needs_update = 0, they all appear to get changed back to 1 on the next sync attempt. Not clear to me what's making that happen.

**Comment by jitendrapurohit** [comment]
>If I change all of those rows to accounts_needs_update = 0, they all appear to get changed back to 1 on the next sync attempt.

@Upperholme could this be due to another sched job running on the site that leads to an update to the contribution? Eg a pull job might fetch the list of invoices from xero and updates the status of contribution in CiviCRM => which leads to accounts_needs_update = 1. Can you try disabling all other xero cron jobs except the push?

>I'm almost certain this is because our people are doing something (either in Civi or in Xero) that the sync can't cope with, but I don't know what it is.

We've seen weird sync errors when users haven't followed the civi-first approach in the past. i.e, merge contact records directly on Xero, create contact and their invoices on xero and then depend on the ext to sync automatically, etc. I think direct contact creation on xero requires another step of mapping the contact in civicrm from `civicrm/a/#/accounts/contact/sync`.

**Comment by jitendrapurohit** [comment]
https://github.com/eileenmcnaughton/nz.co.fuzion.accountsync/pull/53 should be able to fix the problem - 

>If I change all of those rows to accounts_needs_update = 0, they all appear to get changed back to 1 on the next sync attempt.

Can we close this thread?
