### ISSUE TITLE
accounts_modified_date of '0000-00-00 00:00:00' causing grief

### ISSUE THREAD

**Issue by kenwest** [eileenmcnaughton/nz.co.fuzion.civixero#8]
Eileen, in production, when pushing Invoices to Xero, I get an occasional error like ...

    accounts_modified_date is not a valid date: 0000-00-00 00:00:00

I can't reproduce this in test even though I use the same data. (If I could reproduce it I'd raise a PR rather than an issue.) By 'reproduce' I mean I can't create the situation where accounts_modified_date takes on this value.

However, I can stop the error in production by making the following change. It stops CiviXero from setting the data to this 'null' value. If it's worth creating a PR I can do that.

    diff --git a/CRM/Civixero/Invoice.php b/CRM/Civixero/Invoice.php
    index ec485b5..4ef122b 100644
    --- a/CRM/Civixero/Invoice.php
    +++ b/CRM/Civixero/Invoice.php
    @@ -417,7 +417,7 @@ class CRM_Civixero_Invoice extends CRM_Civixero_Base {
         }
         //this will update the last sync date & anything hook-modified
         unset($record['last_sync_date']);
    -    if (empty($record['accounts_modified_date']) || $record['accounts_modified_date'] == '0000-00-00 00:00:00') {
    +    if (empty($record['accounts_modified_date'])) {
           unset($record['accounts_modified_date']);
         }
         civicrm_api3('account_invoice', 'create', $record);

**Comment by eileenmcnaughton** [comment]
That seems harmless enough as a patch - I don't know if it is ideal but if you do a PR for it can you please add a comment & reference this issue for future reference?

**Comment by kenwest** [comment]
Sure
