### ISSUE TITLE
Request for paid assistance

### ISSUE THREAD

**Issue by Upperholme** [eileenmcnaughton/nz.co.fuzion.civixero#80]
We're seeing ongoing problems with our sync to Xero. I think it is probably because we're doing things (or not doing things) that break the tool. We'd love to get an expert eye on the situation to advise us what needs to be done to get it all working smoothly again. Happy to pay for that.

**Comment by petednz** [comment]
Hi Graham - have PM'ed you

**Comment by petednz** [comment]
Fixed via https://github.com/eileenmcnaughton/nz.co.fuzion.accountsync/pull/53 so closing
