### ISSUE TITLE
Breakage in contact.push

### ISSUE THREAD

**Issue by mattwire** [eileenmcnaughton/nz.co.fuzion.civixero#94]
@eileenmcnaughton the comment reads "Undo breakage in contact.push" but gives no clue as to what actually broke?  Can you provide some more detail so I can look into it?

https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/commit/4df0338bc6db92a128f2476e2afd14e631e43287

**Comment by eileenmcnaughton** [comment]
No contacts were pushed - when I put the line back it they were again - I didn't dig futher than that
