### ISSUE TITLE
Authorization failure with CiviXero in CiviCRM in Wordpress

### ISSUE THREAD

**Issue by geoffpkr** [eileenmcnaughton/nz.co.fuzion.civixero#97]
Having difficulty getting CiviXero Authorization to complete in WordPress installation of CiviCRM
I have done this successfully in another installation in Joomla previously and without difficulty.

All steps with OAuth2 were completed and checked several times. 

Error code: 500
Error: unauthorized client : Invalid redirect uri

I noticed the URL link in the CiviXero "Authorize Now" button differs from the URL of the Authorisation Page that I supplied to OAuth2.0 in developer.xero.com but probably only in several wildcards.

Are there any permissions that I might need to change?  Any suggestions gratefully considered.

**Comment by petednz** [comment]
we have it working fine with WP

the civi authorise page on this site is at 

/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fxero%2Fauthorize

the value i see in the App matches ie

/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fxero%2Fauthorize

is that any help

**Comment by geoffpkr** [comment]
Thanks I will keep trying 
Geoff

**Comment by geoffpkr** [comment]
Thanks for your help here - I found the URL read from the CiviXero Auth Page was 
.../wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fxero%2Fauthorize&connector_id=0

I deleted "&connector_id=0" in OAuth2 Redirect URL and works immediately

**Comment by Upperholme** [comment]
It would be helpful if the docs made this clear.
